spring.application.name=hotel
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.jwt.secret=dudameuamor
api.security.jwt.issuer=hotel-api
api.security.jwt.expiration-minutes=60
api.security.jwt.secret=change-me-to-a-very-long-secret-at-least-32-chars
